version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis
    container_name: app
    env_file:
      - .env
    networks:
      - nest-network
    volumes:
      - .:/usr/src/app
    tty: true
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgresql
      - mongodb
      - redis

  postgresql:
    image: postgres:latest
    container_name: postgres
    restart: always
    tty: true
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_USER: ${SQL_USERNAME}
      POSTGRES_DB: ${SQL_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - nest-network
    ports:
      - '${SQL_PORT}:${SQL_PORT}'

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - '8888:8080'
    networks:
      - nest-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    tty: true
    env_file:
      - .env
    volumes:
      - ./mongodata:/data/db
    networks:
      - nest-network
    ports:
      - '${NOSQL_PORT}:${NOSQL_PORT}'

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env
    networks:
      - nest-network
    ports:
      - '${CACHE_PORT}:${CACHE_PORT}'

networks:
  nest-network:
    driver: bridge
