version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: .docker/entrypoint.sh
    container_name: app
    env_file:
      - .env.example
    networks:
      - nest-network
    volumes:
      - .:/usr/app
    tty: true
    ports:
      - '${PORT}:${PORT}'
    links:
      - postgresql
      - mongodb
      - redis
    depends_on:
      - postgresql
      - mongodb
      - redis

  postgresql:
    image: postgres:latest
    container_name: postgres
    restart: always
    tty: true
    env_file:
      - .env.example
    environment:
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_USER: ${SQL_USERNAME}
      POSTGRES_DB: ${SQL_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data
    networks:
      - nest-network
    ports:
      - '${SQL_PORT}:${SQL_PORT}'

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    tty: true
    env_file:
      - .env.example
    volumes:
      - ./.docker/mongodata:/data/db
    networks:
      - nest-network
    ports:
      - '${NOSQL_PORT}:${NOSQL_PORT}'

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env.example
    networks:
      - nest-network
    ports:
      - '${CACHE_PORT}:${CACHE_PORT}'

networks:
  nest-network:
    driver: bridge
