FROM node:14 As development
WORKDIR /usr/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:14-alpine as production
WORKDIR /usr/app
ARG PORT=3333
EXPOSE ${PORT}
COPY --from=development /usr/app/dist .
CMD ["node", "dist/main.js"]

