FROM node:14 As development
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=development
COPY . .
RUN npm run build

FROM node:14-alpine as production
WORKDIR /usr/src/app
COPY . .
COPY --from=development /usr/src/app/dist .
CMD ["node", "dist/main"]

