version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile.prod
    container_name: app
    networks:
      - nest-network
    volumes:
      - .:/usr/share/app
    tty: true
    ports:
      - 3333:3333
    depends_on:
      - postgresql
      - mongodb

  postgresql:
    image: postgres:latest
    container_name: postgres
    restart: always
    tty: true
    volumes:
      - /postgres_data:/var/lib/postgresql/data
    environment: POSTGRES_PASSWORD=postgres
      POSTGRES_DB=development
      POSTGRES_USER=root
    networks:
      - nest-network
    ports:
      - '5432:5432'

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - '8888:8080'
    networks:
      - nest-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    tty: true
    volumes:
      - /mongo_data:/data/db
    networks:
      - nest-network
    ports:
      - '27017:27017'

networks: nest-network
